-- MySQL Script generated by MySQL Workbench
-- 01/17/17 09:26:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema epam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema epam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epam` DEFAULT CHARACTER SET utf8 ;
USE `epam` ;

-- -----------------------------------------------------
-- Table `epam`.`app_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epam`.`app_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `sso_id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sso_id_UNIQUE` (`sso_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `epam`.`user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epam`.`user_profile` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `epam`.`app_user_user_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `epam`.`app_user_user_profile` (
  `user_id` BIGINT(20) NOT NULL,
  `user_profile_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`user_id`, `user_profile_id`),
  INDEX `FK_USER_PROFILE_idx` (`user_profile_id` ASC),
  CONSTRAINT `FK_APP_USER`
    FOREIGN KEY (`user_id`)
    REFERENCES `epam`.`app_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_USER_PROFILE`
    FOREIGN KEY (`user_profile_id`)
    REFERENCES `epam`.`user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
